#!/bin/bash

# ~~ mklink E:\SVN\the-boilerplate\.git\modules\packages\js-boilerplate-shared\hooks\pre-commit E:\SVN\the-boilerplate\packages\js-boilerplate-shared\git-hooks\pre-commit

source /e/scripts/git/hooks/version-1/setup-colors || exit 1

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

# Replace possible paths to .git hooks based on context.
DIR=${DIR//\/.git}
DIR=${DIR//\/modules/}
DIR=${DIR//\/hooks/}

cd "${DIR}" || exit 1;

function js_tests() {
    # Run JS te
    echo "${YELLOW}[pre-commit]${BLUE} Running JS Tests... ${WHITE}"

    OUTPUT=$(yarn run test --bail 2>&1)
     if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}JS Tests failed. Fix the error before commit!"
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} JS Tests Passed!${RESET_COLOR}"

}
#####  js_tests &


function js_lint() {
    echo "${YELLOW}[pre-commit]${BLUE} Running ES Lint... ${WHITE}"
    OUTPUT=$(yarn lint --fix=false 2>&1)
    if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}JS Lint failed. Fix the error before commit!"
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} JS Lint Passed!${RESET_COLOR}"
}
js_lint &


function validate_ts() {
    echo "${YELLOW}[pre-commit]${BLUE} Validating TS definitions... ${WHITE}"

    OUTPUT=$(yarn run validate-ts 2>&1)
     if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}TS validation failed. Fix the error before commit!"
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} TS validation Passed!${RESET_COLOR}"

}
validate_ts &

function js_build() {
    echo "${YELLOW}[pre-commit]${BLUE} Running \`yarn build\`... ${WHITE}"
    OUTPUT=$(yarn build 2>&1)
    if [[ $? != 0 ]]; then
        echo
        echo "${BLUE}JS Build failed."
        echo "${RED}$OUTPUT"
        exit_reset_colors
    fi
    echo "${YELLOW}[pre-commit]${GREEN} Yarn Build Completed!${RESET_COLOR}"
}
js_build &

source /e/scripts/git/hooks/version-1/wait-for-jobs || exit 1
