import fs from 'fs';
import os from 'os';
import path from 'path';
import {generateModuleTypeDefinition, writeTypingsFile} from '../../../lib/css-module-types.js';


describe( 'generateModuleTypeDefinition', () => {
	it( 'generates a definition for plain class names', () => {
		expect( generateModuleTypeDefinition( [ 'root', 'title' ], 'SiteHeader' ) ).toBe( `// Autogenerated by lipemat:css-module-types.
declare namespace SiteHeaderNamespace {
	export interface ISiteHeader {
		root: string;
		title: string;
	}
}

declare const SiteHeaderModule: SiteHeaderNamespace.ISiteHeader;

export = SiteHeaderModule;
` );
	} );


	it( 'quotes class names containing hyphens', () => {
		const output = generateModuleTypeDefinition( [ 'is-active' ], 'Button' );

		expect( output ).toContain( '\t\t\'is-active\': string;' );
	} );


	it( 'sorts class names alphabetically', () => {
		const output = generateModuleTypeDefinition( [ 'zebra', 'apple', 'mango' ], 'Fruit' );

		expect( output.indexOf( 'apple: string;' ) ).toBeLessThan( output.indexOf( 'mango: string;' ) );
		expect( output.indexOf( 'mango: string;' ) ).toBeLessThan( output.indexOf( 'zebra: string;' ) );
	} );


	it( 'leaves the input array in its original order', () => {
		const keys = [ 'zebra', 'apple' ];

		generateModuleTypeDefinition( keys, 'Fruit' );

		expect( keys ).toEqual( [ 'zebra', 'apple' ] );
	} );


	it( 'generates an empty interface for no class names', () => {
		const output = generateModuleTypeDefinition( [], 'Empty' );

		expect( output ).toContain( 'export interface IEmpty {' );
		expect( output ).not.toContain( ': string;' );
	} );


	it( 'handles unicode class names', () => {
		const output = generateModuleTypeDefinition( [ 'über-cool', 'café' ], 'Menu' );

		expect( output ).toContain( '\t\t\'über-cool\': string;' );
		expect( output ).toContain( '\t\tcafé: string;' );
	} );
} );


describe( 'writeTypingsFile', () => {
	let tempDir: string;

	beforeEach( () => {
		tempDir = fs.mkdtempSync( path.join( os.tmpdir(), 'css-module-types-' ) );
	} );

	afterEach( () => {
		fs.rmSync( tempDir, {recursive: true, force: true} );
	} );


	it( 'writes a new typings file', () => {
		const fileName = path.join( tempDir, 'new.pcss.d.ts' );

		writeTypingsFile( fileName, 'fresh content' );

		expect( fs.readFileSync( fileName, 'utf8' ) ).toBe( 'fresh content' );
	} );


	it( 'overwrites a typings file when content changed', () => {
		const fileName = path.join( tempDir, 'changed.pcss.d.ts' );
		fs.writeFileSync( fileName, 'old content' );

		writeTypingsFile( fileName, 'new content' );

		expect( fs.readFileSync( fileName, 'utf8' ) ).toBe( 'new content' );
	} );


	it( 'leaves an unchanged typings file untouched', () => {
		const fileName = path.join( tempDir, 'same.pcss.d.ts' );
		fs.writeFileSync( fileName, 'same content' );
		const past = new Date( '2000-01-01T00:00:00Z' );
		fs.utimesSync( fileName, past, past );

		writeTypingsFile( fileName, 'same content' );

		expect( fs.statSync( fileName ).mtime ).toEqual( past );
	} );
} );
