#!/bin/bash
######################################################
#
# Prepend the current branch name to every commit message.
#
# @version 2.2.1
#
######################################################

# ~~ mklink E:\SVN\the-boilerplate\.git\modules\packages\js-boilerplate-shared\hooks\prepare-commit-msg E:\SVN\the-boilerplate\packages\js-boilerplate-shared\dev\git-hooks\prepare-commit-msg

source /e/scripts/git/hooks/version-1/prepare-commit-msg
